//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Our Weather App.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our weather app, your go-to destination for up-to-date weather information! Our app is designed to provide you with accurate and reliable weather forecasts, making it easier for you to plan your day, week, or even the next 24 hours..
        /// </summary>
        internal static string About_Info {
            get {
                return ResourceManager.GetString("About_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broken clouds.
        /// </summary>
        internal static string broken_clouds {
            get {
                return ResourceManager.GetString("broken clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear sky.
        /// </summary>
        internal static string clear_sky {
            get {
                return ResourceManager.GetString("clear sky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Days Weather.
        /// </summary>
        internal static string Days6Menu {
            get {
                return ResourceManager.GetString("Days6Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drizzle.
        /// </summary>
        internal static string drizzle {
            get {
                return ResourceManager.GetString("drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drizzle rain.
        /// </summary>
        internal static string drizzle_rain {
            get {
                return ResourceManager.GetString("drizzle rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust.
        /// </summary>
        internal static string dust {
            get {
                return ResourceManager.GetString("dust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust whirls.
        /// </summary>
        internal static string dust_whirls {
            get {
                return ResourceManager.GetString("dust whirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extreme rain.
        /// </summary>
        internal static string extreme_rain {
            get {
                return ResourceManager.GetString("extreme rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to few clouds.
        /// </summary>
        internal static string few_clouds {
            get {
                return ResourceManager.GetString("few clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fog.
        /// </summary>
        internal static string fog {
            get {
                return ResourceManager.GetString("fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freezing rain.
        /// </summary>
        internal static string freezing_rain {
            get {
                return ResourceManager.GetString("freezing rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haze.
        /// </summary>
        internal static string haze {
            get {
                return ResourceManager.GetString("haze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy intensity drizzle.
        /// </summary>
        internal static string heavy_intensity_drizzle {
            get {
                return ResourceManager.GetString("heavy intensity drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy intensity drizzle rain.
        /// </summary>
        internal static string heavy_intensity_drizzle_rain {
            get {
                return ResourceManager.GetString("heavy intensity drizzle rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy intensity shower rain.
        /// </summary>
        internal static string heavy_intensity_shower_rain {
            get {
                return ResourceManager.GetString("heavy intensity shower rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy shower rain and drizzle.
        /// </summary>
        internal static string heavy_shower_rain_and_drizzle {
            get {
                return ResourceManager.GetString("heavy shower rain and drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy shower snow.
        /// </summary>
        internal static string heavy_shower_snow {
            get {
                return ResourceManager.GetString("heavy shower snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy snow.
        /// </summary>
        internal static string heavy_snow {
            get {
                return ResourceManager.GetString("heavy snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy thunderstorm.
        /// </summary>
        internal static string heavy_thunderstorm {
            get {
                return ResourceManager.GetString("heavy thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hours Weather.
        /// </summary>
        internal static string Hours24Menu {
            get {
                return ResourceManager.GetString("Hours24Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light intensity drizzle.
        /// </summary>
        internal static string light_intensity_drizzle {
            get {
                return ResourceManager.GetString("light intensity drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light intensity drizzle rain.
        /// </summary>
        internal static string light_intensity_drizzle_rain {
            get {
                return ResourceManager.GetString("light intensity drizzle rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light rain.
        /// </summary>
        internal static string light_rain {
            get {
                return ResourceManager.GetString("light rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light rain and snow.
        /// </summary>
        internal static string light_rain_and_snow {
            get {
                return ResourceManager.GetString("light rain and snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light shower sleet.
        /// </summary>
        internal static string light_shower_sleet {
            get {
                return ResourceManager.GetString("light shower sleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light shower snow.
        /// </summary>
        internal static string light_shower_snow {
            get {
                return ResourceManager.GetString("light shower snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light snow.
        /// </summary>
        internal static string light_snow {
            get {
                return ResourceManager.GetString("light snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light thunderstorm.
        /// </summary>
        internal static string light_thunderstorm {
            get {
                return ResourceManager.GetString("light thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mist.
        /// </summary>
        internal static string mist {
            get {
                return ResourceManager.GetString("mist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate rain.
        /// </summary>
        internal static string moderate_rain {
            get {
                return ResourceManager.GetString("moderate rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast clouds.
        /// </summary>
        internal static string overcast_clouds {
            get {
                return ResourceManager.GetString("overcast clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ragged shower rain.
        /// </summary>
        internal static string ragged_shower_rain {
            get {
                return ResourceManager.GetString("ragged shower rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ragged thunderstorm.
        /// </summary>
        internal static string ragged_thunderstorm {
            get {
                return ResourceManager.GetString("ragged thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain.
        /// </summary>
        internal static string rain {
            get {
                return ResourceManager.GetString("rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain and snow.
        /// </summary>
        internal static string rain_and_snow {
            get {
                return ResourceManager.GetString("rain and snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sand.
        /// </summary>
        internal static string sand {
            get {
                return ResourceManager.GetString("sand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scattered clouds.
        /// </summary>
        internal static string scattered_clouds {
            get {
                return ResourceManager.GetString("scattered clouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower drizzle.
        /// </summary>
        internal static string shower_drizzle {
            get {
                return ResourceManager.GetString("shower drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower rain.
        /// </summary>
        internal static string shower_rain {
            get {
                return ResourceManager.GetString("shower rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower rain and drizzle.
        /// </summary>
        internal static string shower_rain_and_drizzle {
            get {
                return ResourceManager.GetString("shower rain and drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower sleet.
        /// </summary>
        internal static string shower_sleet {
            get {
                return ResourceManager.GetString("shower sleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower snow.
        /// </summary>
        internal static string shower_snow {
            get {
                return ResourceManager.GetString("shower snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleet.
        /// </summary>
        internal static string sleet {
            get {
                return ResourceManager.GetString("sleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smoke.
        /// </summary>
        internal static string smoke {
            get {
                return ResourceManager.GetString("smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow.
        /// </summary>
        internal static string snow {
            get {
                return ResourceManager.GetString("snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squalls.
        /// </summary>
        internal static string squall {
            get {
                return ResourceManager.GetString("squall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm.
        /// </summary>
        internal static string thunderstorm {
            get {
                return ResourceManager.GetString("thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with drizzle.
        /// </summary>
        internal static string thunderstorm_with_drizzle {
            get {
                return ResourceManager.GetString("thunderstorm with drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with heavy drizzle.
        /// </summary>
        internal static string thunderstorm_with_heavy_drizzle {
            get {
                return ResourceManager.GetString("thunderstorm with heavy drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with heavy rain.
        /// </summary>
        internal static string thunderstorm_with_heavy_rain {
            get {
                return ResourceManager.GetString("thunderstorm with heavy rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with light drizzle.
        /// </summary>
        internal static string thunderstorm_with_light_drizzle {
            get {
                return ResourceManager.GetString("thunderstorm with light drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with light rain.
        /// </summary>
        internal static string thunderstorm_with_light_rain {
            get {
                return ResourceManager.GetString("thunderstorm with light rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm with rain.
        /// </summary>
        internal static string thunderstorm_with_rain {
            get {
                return ResourceManager.GetString("thunderstorm with rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherApp.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tornado.
        /// </summary>
        internal static string tornado {
            get {
                return ResourceManager.GetString("tornado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very heavy rain.
        /// </summary>
        internal static string very_heavy_rain {
            get {
                return ResourceManager.GetString("very heavy rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volcanic ash.
        /// </summary>
        internal static string volcanic_ash {
            get {
                return ResourceManager.GetString("volcanic ash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
